#!/bin/bash

TYPE="mbr"

SITE_ROOT=$(realpath $(dirname $(realpath $0))/..)

export HOME=$SITE_ROOT

if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
source $SITE_ROOT/scripts/base.sh

cd $SITE_ROOT

mbr_root=/massbit/massbitroute/app
service_dir=$mbr_root/src/sites/services

export MBR_ENV=${MBR_ENV:-dev}
export BRANCH=${BRANCH:-dev}
export MBRAPP_BRANCH=${MBRAPP_BRANCH:-dev}
export GBC_BRANCH=${GBC_BRANCH:-dev}
export ASDF_BRANCH=${ASDF_BRANCH:-dev}
export SSL_BRANCH=${SSL_BRANCH:-dev}
export GWMAN_BRANCH=${GWMAN_BRANCH:-dev}
export NODE_BRANCH=${NODE_BRANCH:-dev}
export GATEWAY_BRANCH=${GATEWAY_BRANCH:-dev}
export STAT_BRANCH=${STAT_BRANCH:-dev}
export MONITOR_BRANCH=${MONITOR_BRANCH:-dev}
export API_BRANCH=${API_BRANCH:-dev}
export SESSION_BRANCH=${SESSION_BRANCH:-dev}
export GIT_BRANCH=${GIT_BRANCH:-dev}
export MKAGENT_BRANCH=${MKAGENT_BRANCH:-dev}

# $service_dir/gwman|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gwman.git|$GWMAN_BRANCH \
#  $service_dir/api|$GIT_PUBLIC_URL/massbitprotocol/massbitroute.git|$API_BRANCH \
#  $service_dir/session|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_session.git|$SESSION_BRANCH \
#  $service_dir/stat|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_stat.git|$STAT_BRANCH \
#  $service_dir/node|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_node.git|$NODE_BRANCH \
#  $service_dir/gateway|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gateway.git|$GATEWAY_BRANCH \
#  $service_dir/monitor|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_monitor.git|$MONITOR_BRANCH \
#  $service_dir/mkagent|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_mkagent.git|$MKAGENT_BRANCH \
#  $service_dir/git|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_git.git|$GIT_BRANCH \
_repo() {
	REPOS="\
$SITE_ROOT/env|$GIT_PRIVATE_READ_URL/massbitroute/env.git|$MBR_ENV \
 $mbr_root/gbc|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc|$MBR_ENV \
 $mbr_root/src|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_dev.git|$MBR_ENV \
"
}
_repo

_prepare() {
	echo "Prepare"
	mkdir -p $SITE_ROOT/logs/nginx $SITE_ROOT/db $SITE_ROOT/tmp $SITE_ROOT/db
	rm -rf $SITE_ROOT/tmp/*
	_git_clone $GIT_PRIVATE_READ_URL/massbitroute/env.git /massbit/massbitroute/app/src/env $BRANCH

	source $SITE_ROOT/.env

	_git_clone $GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc.git $mbr_root/gbc
	# _git_clone https://github.com/massbitprotocol/massbitroute_asdf $mbr_root/gbc/bin/.asdf $ASDF_BRANCH

	bash $SITE_ROOT/cmd_server _env
	source $SITE_ROOT/.env_raw
	_repo
}

_install_repos() {
	_git_config
	_repo
	for _pathgit in $REPOS; do
		_path=$(echo $_pathgit | cut -d'|' -f1)
		_url=$(echo $_pathgit | cut -d'|' -f2)
		_branch=$(echo $_pathgit | cut -d'|' -f3)
		_git_clone $_url $_path $_branch
	done
}

_modules() {
	_cmd=$1
	_st_modules=0
	if [ "$SITE_ROOT/.module_paths" ]; then
		cat "$SITE_ROOT/.module_paths" | while read _m; do
			_sc="$_m/scripts/run"
			if [ -f "$_sc" ]; then
				echo "$_m/scripts/run" $_cmd
				bash -x "$_m/scripts/run" $_cmd
				if [ $_st_modules -ne 0 ]; then
					_st_modules=$?
				fi
			fi
		done
	fi
	return $_st_modules

}

_supervisor() {
	ln -sf /massbit/massbitroute/app/gbc /massbit/massbitroute/app/src/gbc
	ln -sf /massbit/massbitroute/app/gbc/bin/openresty /usr/local/openresty
	apt-get update
	apt-get install -y git apache2-utils supervisor jq python-is-python2 libssl-dev libmaxminddb-dev

	/etc/init.d/supervisor start
	systemctl enable supervisor
	systemctl start supervisor

	mkdir -p /etc/supervisor/conf.d
	cp supervisor.conf /etc/supervisor/conf.d/${TYPE}.conf
	supervisorctl update
	supervisorctl status
	$SITE_ROOT/cmd_server status
}
_init() {
	echo "Init"
	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
		echo "Need GIT_PRIVATE_READ_URL"
		exit 1
	fi
	if [ ! -f "$SITE_ROOT/.env" ]; then
		echo "$MBR_ENV" >$SITE_ROOT/.env
	fi

	source $SITE_ROOT/.env

	_git_clone $GIT_PRIVATE_READ_URL/massbitroute/env.git /massbit/massbitroute/app/src/env $MBR_ENV
	_git_clone $GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc.git /massbit/massbitroute/app/gbc

	bash $SITE_ROOT/cmd_server _env
	source $SITE_ROOT/.env_raw
	_repo

}
_install() {
	echo "Install"
	_init
	_prepare
	_install_repos
	# _modules _install_one
	_supervisor
}

_update() {
	echo "Update"
	_st_update=0
	_update_repos
	_st_update=$?

	_modules _update
	_st_modules=$?

	if [ $_st_modules -ne 0 ]; then
		_st_update=$_st_modules
	fi
	return $_st_update
}

_monitor() {
	echo "Monitor"
	_update
	is_reload=$?

	if [ $is_reload -ne 0 ]; then
		$0 _reload
	fi
}
_run() {
	echo "Running"
	rm -rf $SITE_ROOT/tmp/*
	$SITE_ROOT/start_server
}

$@
