# version: "2"
services:
  basenode:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_basenode_dev:_VER_-_BRANCH_-_ENV_
    command: ""
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/base/Dockerfile_basenode._ENV_
      args:
        BRANCH: _BRANCH_
    container_name: mbr_basenode
    
  base:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_base_dev:_VER_-_BRANCH_-_ENV_
    command: ""
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/base/Dockerfile._ENV_
      args:
        BRANCH: _BRANCH_
    container_name: mbr_base
    
  api:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_api_dev:_VER_-_BRANCH_-_ENV_
    command: "-n"
    hostname: "api"
    domainname: "massbitroute.net"    
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/api/Dockerfile._ENV_
      args:
        VERSION: _VER_-_BRANCH_-_ENV_
        BRANCH: _BRANCH_
    container_name: mbr_api
    # network_mode: "host"
    # ports:
    #   - "443:443"
    volumes:
      - /massbit/massbitroute/app/src/sites/services/api_local:/massbit/massbitroute/app/src/sites/services/api:rw
      - ./run/api/logs:/massbit/massbitroute/app/src/sites/services/api/logs:rw
      - ./run/api/vars:/massbit/massbitroute/app/src/sites/services/api/vars:rw
      - ./run/api/db:/massbit/massbitroute/app/src/sites/services/api/db:rw
    environment:
      - MBR_ENV=_BRANCH_
      - GIT_PRIVATE_READ_URL=http://massbit:NnKufW7-xMyt5mKzmMt5Q7Stg7HefHTC@git.massbitroute.net
    extra_hosts:
      - "git.massbitroute.net:172.20.0.2"
      - "api.massbitroute.net:172.20.0.3"      
    networks:
      mbr_core:
       ipv4_address: 172.20.0.3
  git:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_git_dev:_VER_-_BRANCH_-_ENV_
    command: "-n"
    hostname: "git"
    domainname: "massbitroute.net"
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/git/Dockerfile._ENV_
      args:
        VERSION: _VER_-_BRANCH_-_ENV_
        BRANCH: _BRANCH_
    container_name: mbr_git    
    volumes:
      - ./run/git/data:/massbit/massbitroute/app/src/sites/services/git/data:rw
      - ./run/git/logs:/massbit/massbitroute/app/src/sites/services/git/logs:rw
      - ./run/git/vars:/massbit/massbitroute/app/src/sites/services/git/vars:rw
      - ./run/git/db:/massbit/massbitroute/app/src/sites/services/git/db:rw
    environment:
      - MBR_ENV=_BRANCH_
    extra_hosts:
      - "git.massbitroute.net:172.20.0.2"
      - "api.massbitroute.net:172.20.0.3"
    networks:
      mbr_core:
       ipv4_address: 172.20.0.2
  gwman:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_gwman_dev:_VER_-_BRANCH_-_ENV_
    command: "-n"
    hostname: "gwman"
    domainname: "massbitroute.net"        
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/gwman/Dockerfile._ENV_
      args:
        VERSION: _VER_-_BRANCH_-_ENV_
        BRANCH: _BRANCH_
    container_name: mbr_gwman  
    volumes:
      - ./run/gwman/logs:/massbit/massbitroute/app/src/sites/services/gwman/logs:rw
      - ./run/gwman/vars:/massbit/massbitroute/app/src/sites/services/gwman/vars:rw
      - ./run/gwman/db:/massbit/massbitroute/app/src/sites/services/gwman/db:rw
    environment:
      - MBR_ENV=_BRANCH_
      - GIT_PRIVATE_READ_URL=http://massbit:NnKufW7-xMyt5mKzmMt5Q7Stg7HefHTC@git.massbitroute.net      

    extra_hosts:
      - "git.massbitroute.net:172.20.0.2"
      - "api.massbitroute.net:172.20.0.3"
    networks:
      mbr_core:
       ipv4_address: 172.20.0.4
       
  stat-eth-mainnet:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_stat_dev:_VER_-_BRANCH_-_ENV_
    command: "-n"
    hostname: "eth-mainnet.stat.mbr"
    domainname: "massbitroute.net"    
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/stat/Dockerfile._ENV_
      args:
        VERSION: _VER_-_BRANCH_-_ENV_        
        BRANCH: _BRANCH_
    container_name: mbr_stat    
    volumes:
      - ./run/stat/logs:/massbit/massbitroute/app/src/sites/services/stat/logs:rw
      - ./run/stat/vars:/massbit/massbitroute/app/src/sites/services/stat/vars:rw
      - ./run/stat/db:/massbit/massbitroute/app/src/sites/services/stat/db:rw
    environment:
      - STAT_TYPE=node
      - STAT_NETWORK=eth
      - STAT_BLOCKCHAIN=mainnet
      - MBR_ENV=_BRANCH_
      - GIT_PRIVATE_READ_URL=http://massbit:NnKufW7-xMyt5mKzmMt5Q7Stg7HefHTC@git.massbitroute.net            
    networks:
      - mbr_core      
      
  monitor-eth-mainnet:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_monitor_dev:_VER_-_BRANCH_-_ENV_
    command: "-n"
    hostname: "eth-mainnet.monitor.mbr"
    domainname: "massbitroute.net"        
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/monitor/Dockerfile._ENV_
      args:
        VERSION: _VER_-_BRANCH_-_ENV_        
        BRANCH: _BRANCH_
    container_name: mbr_monitor
    volumes:
      - ./run/monitor/logs:/massbit/massbitroute/app/src/sites/services/monitor/logs:rw
      - ./run/monitor/vars:/massbit/massbitroute/app/src/sites/services/monitor/vars:rw
      - ./run/monitor/db:/massbit/massbitroute/app/src/sites/services/monitor/db:rw
    environment:
      - MONITOR_TYPES=node
      - MONITOR_NETWORKS=eth
      - MONITOR_BLOCKCHAINS=mainnet
      - MBR_ENV=_BRANCH_
      - GIT_PRIVATE_READ_URL=http://massbit:NnKufW7-xMyt5mKzmMt5Q7Stg7HefHTC@git.massbitroute.net                  
    networks:
      - mbr_core      
      
  gateway:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_gateway_dev:_VER_-_BRANCH_-_ENV_
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/gateway/Dockerfile._ENV_
      args:
        VERSION: _VER_-_BRANCH_-_ENV_
        BRANCH: _BRANCH_
    container_name: mbr_gateway
    volumes:
      - ./run/gateway/logs:/massbit/massbitroute/app/src/sites/services/gateway/logs:rw
    environment:
      - MBR_ENV=_BRANCH_
      - INSTALL_CMD=https://portal.massbitroute.net/api/v1/gateway_install?id=89f24596-8087-4406-87a4-aec47ff2b4d7&user_id=b363ddf4-42cf-4ccf-89c2-8c42c531ac99&blockchain=eth&network=mainnet&zone=EU&app_key=LFyHE_WaDS6HiQuE6QqKSA&portal_url=https://portal.massbitroute.net&env=keiko
    networks:
      - mbr_gateway
      
  node:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_node_dev:_VER_-_BRANCH_-_ENV_
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/node/Dockerfile._ENV_
      args:
        VERSION: _VER_-_BRANCH_-_ENV_
        BRANCH: _BRANCH_
    container_name: mbr_node
    volumes:
      - ./run/node/logs:/massbit/massbitroute/app/src/sites/services/node/logs:rw
    environment:
      - MBR_ENV=_BRANCH_
      - INSTALL_CMD=https://portal.massbitroute.net/api/v1/node_install?id=139aa103-96fb-4000-8a5f-cc8650298037&user_id=b363ddf4-42cf-4ccf-89c2-8c42c531ac99&blockchain=eth&network=mainnet&zone=EU&data_url=http://34.81.232.186:8545&app_key=y8OaDKRL-vdBkd5zXNsSwA&portal_url=https://portal.massbitroute.net&env=keiko
    networks:
      - mbr_node    

networks:
  mbr_core:
    ipam:
      config:
        - subnet: 172.20.0.0/24    
  mbr_node:
    ipam:
      config:
        - subnet: 172.30.0.0/24    
  mbr_gateway:
    ipam:
      config:
        - subnet: 172.40.0.0/24    
