# version: "2"
services:
  basenode:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_basenode_dev:0.0.1-shamu-dev
    command: ""
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/base/Dockerfile_basenode.dev
      args:
        BRANCH: shamu
    container_name: mbr_basenode
    
  base:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_base_dev:0.0.1-shamu-dev
    command: ""
    build:
      context: /massbit/massbitroute/app/src
      dockerfile: install/mbr/build/base/Dockerfile.dev
      args:
        BRANCH: shamu
        GIT_PRIVATE_READ_URL: http://massbit:DaTR__SGr89IjgvcwBtJyg0v_DFySDwI@git.massbitroute.net
    container_name: mbr_base
    
  api:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_api_dev:0.0.1-shamu-dev
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src/sites/services/api
      dockerfile: install/mbr/build/api/Dockerfile.dev
      args:
        BRANCH: shamu
        GIT_PRIVATE_READ_URL: http://massbit:DaTR__SGr89IjgvcwBtJyg0v_DFySDwI@git.massbitroute.net
    container_name: mbr_api
    # network_mode: "host"
    # ports:
    #   - "443:443"
    volumes:
      - ./api/logs:/massbit/massbitroute/app/src/sites/services/git/logs:rw
      - ./api/vars:/massbit/massbitroute/app/src/sites/services/git/vars:rw
      # - ./api/tmp:/massbit/massbitroute/app/src/sites/services/git/tmp:rw
      - ./api/db:/massbit/massbitroute/app/src/sites/services/git/db:rw
    environment:
      - MBR_ENV=shamu  
  git:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_git_dev:0.0.1-shamu-dev
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src/sites/services/git
      dockerfile: install/mbr/build/git/Dockerfile.dev
      args:
        BRANCH: shamu
    container_name: mbr_git    
    volumes:
      - ./git/deploy:/massbit/massbitroute/app/src/sites/services/git/deploy:rw      
      - ./git/logs:/massbit/massbitroute/app/src/sites/services/git/logs:rw
      - ./git/vars:/massbit/massbitroute/app/src/sites/services/git/vars:rw
      # - ./git/tmp:/massbit/massbitroute/app/src/sites/services/git/tmp:rw
      - ./git/db:/massbit/massbitroute/app/src/sites/services/git/db:rw
    environment:
      - MBR_ENV=shamu
  gwman:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_gwman_dev:0.0.1-shamu-dev
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src/sites/services/gwman
      dockerfile: install/mbr/build/gwman/Dockerfile.dev
      args:
        BRANCH: shamu
        GIT_PRIVATE_READ_URL: http://massbit:DaTR__SGr89IjgvcwBtJyg0v_DFySDwI@git.massbitroute.net        
    container_name: mbr_gwman  
    volumes:
      - ./gwman/logs:/massbit/massbitroute/app/src/sites/services/gwman/logs:rw
      - ./gwman/vars:/massbit/massbitroute/app/src/sites/services/gwman/vars:rw
      - ./gwman/db:/massbit/massbitroute/app/src/sites/services/gwman/db:rw
    environment:
      - MBR_ENV=shamu      
  stat:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_stat_dev:0.0.1-shamu-dev
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src/sites/services/stat
      dockerfile: install/mbr/build/stat/Dockerfile.dev
      args:
        BRANCH: shamu
        GIT_PRIVATE_READ_URL: http://massbit:DaTR__SGr89IjgvcwBtJyg0v_DFySDwI@git.massbitroute.net        
    container_name: mbr_stat    
    volumes:
      - ./stat/logs:/massbit/massbitroute/app/src/sites/services/stat/logs:rw
      - ./stat/vars:/massbit/massbitroute/app/src/sites/services/stat/vars:rw
      # - ./stat/tmp:/massbit/massbitroute/app/src/sites/services/stat/tmp:rw
      - ./stat/db:/massbit/massbitroute/app/src/sites/services/stat/db:rw
    environment:
      - MBR_ENV=shamu      
  monitor:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_monitor_dev:0.0.1-shamu-dev
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src/sites/services/monitor
      dockerfile: install/mbr/build/monitor/Dockerfile.dev
      args:
        BRANCH: shamu
        GIT_PRIVATE_READ_URL: http://massbit:DaTR__SGr89IjgvcwBtJyg0v_DFySDwI@git.massbitroute.net        
    container_name: mbr_monitor
    volumes:
      - ./monitor/logs:/massbit/massbitroute/app/src/sites/services/monitor/logs:rw
      - ./monitor/vars:/massbit/massbitroute/app/src/sites/services/monitor/vars:rw
      # - ./monitor/tmp:/massbit/massbitroute/app/src/sites/services/monitor/tmp:rw
      - ./monitor/db:/massbit/massbitroute/app/src/sites/services/monitor/db:rw
    environment:
      - MBR_ENV=shamu
  gateway:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_gateway_dev:0.0.1-shamu-dev
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src/sites/services/gateway
      dockerfile: install/mbr/build/gateway/Dockerfile.dev
      args:
        VERSION: 0.0.1-shamu-dev
        BRANCH: shamu
    container_name: mbr_gateway
    volumes:
      - ./gateway/logs:/massbit/massbitroute/app/src/sites/services/gateway/logs:rw
    environment:
      - MBR_ENV=shamu
      - INSTALL_CMD=https://portal.massbitroute.net/api/v1/gateway_install?id=89f24596-8087-4406-87a4-aec47ff2b4d7&user_id=b363ddf4-42cf-4ccf-89c2-8c42c531ac99&blockchain=eth&network=mainnet&zone=EU&app_key=LFyHE_WaDS6HiQuE6QqKSA&portal_url=https://portal.massbitroute.net&env=keiko
  node:
    privileged: true
    restart: unless-stopped
    image: massbit/massbitroute_node_dev:0.0.1-shamu-dev
    command: "-n"
    build:
      context: /massbit/massbitroute/app/src/sites/services/node
      dockerfile: install/mbr/build/node/Dockerfile.dev
      args:
        VERSION: 0.0.1-shamu-dev
        BRANCH: shamu
    container_name: mbr_node
    volumes:
      - ./node/logs:/massbit/massbitroute/app/src/sites/services/node/logs:rw
    environment:
      - MBR_ENV=shamu
      - INSTALL_CMD=https://portal.massbitroute.net/api/v1/node_install?id=139aa103-96fb-4000-8a5f-cc8650298037&user_id=b363ddf4-42cf-4ccf-89c2-8c42c531ac99&blockchain=eth&network=mainnet&zone=EU&data_url=http://34.81.232.186:8545&app_key=y8OaDKRL-vdBkd5zXNsSwA&portal_url=https://portal.massbitroute.net&env=keiko
      
